services:
  - type: web
    name: adamauto
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn AdamAuto.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: adamauto_db
          property: connectionString

databases:
  - name: adamautomotive_wrotelook
    databaseName: adamautomotive_wrotelook
    user: adamautomotive_wrotelook