# Generated by Django 5.0.6 on 2024-08-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_tbl_company_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_color',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='tbl_model',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
