# Generated by Django 5.0.6 on 2024-08-07 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_vehicletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_type', models.CharField(max_length=100)),
                ('kilometers', models.IntegerField()),
                ('transmission', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=100)),
                ('insurance_validity', models.DateField()),
                ('pollution_validity', models.DateField()),
                ('tax_validity', models.DateField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.vehicletype')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.tbl_color')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.tbl_company')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.tbl_model')),
            ],
        ),
    ]
