# Generated by Django 5.0.6 on 2024-08-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_carimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
