# Generated by Django 5.0.6 on 2024-08-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_carimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
