# Generated by Django 5.0.6 on 2024-08-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0014_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
