# Generated by Django 5.0.6 on 2024-08-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0015_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disable_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
