# Generated by Django 5.0.6 on 2024-08-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_user_disable_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disable_reason',
        ),
    ]
