# Generated by Django 5.0.6 on 2024-08-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_remove_user_disable_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
