# Generated by Django 5.0.6 on 2024-08-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_remove_usercardetails_image_servicebooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBooking',
        ),
    ]
