# Generated by Django 5.0.6 on 2024-08-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0025_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='would_recommend',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=5, null=True),
        ),
    ]
