# Generated by Django 5.0.6 on 2024-08-31 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0026_alter_feedback_would_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Users.usercardetails'),
        ),
    ]
