# Generated by Django 5.0.6 on 2024-09-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0030_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.BigIntegerField(),
        ),
    ]
