# Generated by Django 5.0.6 on 2024-09-08 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0031_alter_order_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
