# Generated by Django 5.0.6 on 2024-09-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0033_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
