# Generated by Django 5.0.6 on 2024-09-08 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0035_carpurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarPurchase',
        ),
    ]
