# Generated by Django 5.0.6 on 2024-09-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0037_feedback_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='would_recommend',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe')], max_length=5, null=True),
        ),
    ]
