# Generated by Django 5.0.6 on 2024-09-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0038_alter_feedback_would_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='would_recommend',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No'), ('2', 'Maybe')], max_length=5, null=True),
        ),
    ]
