# Generated by Django 5.0.6 on 2024-09-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0039_alter_feedback_would_recommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='would_recommend',
        ),
    ]
