# Generated by Django 5.0.6 on 2024-09-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0042_alter_carpurchase_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpurchase',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='carpurchase',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='carpurchase',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='carpurchase',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
