# Generated by Django 5.0.6 on 2024-09-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0043_carpurchase_aadhar_number_carpurchase_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpurchase',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
